### ISSUE TITLE
smpl & smplx shape

### ISSUE THREAD

**Issue by shanemankiw** [generalizable-neural-performer/bodyfitting#2]
Hi, 

Thanks for the great work. Encountered a problem when i tried to run on genebody dataset:

When I set body type as 'smplx', the error is:

> Traceback (most recent call last):
>   File "apps/genebody_fitting.py", line 197, in <module>
>     myrunner.run()
>   File "apps/genebody_fitting.py", line 187, in run
>     self.run_smplify(frame, data, keypoints)
>   File "apps/genebody_fitting.py", line 167, in run_smplify
>     use_mask=self.use_mask, masks=masks, mask_frames=mask_frames, output_folder=output_dir)
>   File "/home/wjh/nerf/code/bodyfitting/smplify/body_fitting.py", line 91, in __call__
>     use_mesh=use_mesh, meshfile=meshfile, displacement=disp)
>   File "/home/wjh/nerf/code/bodyfitting/smplify/smplify.py", line 187, in __call__
>     return_full_pose=True)
>   File "/home/wjh/anaconda3/envs/human/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/wjh/anaconda3/envs/human/lib/python3.6/site-packages/smplx/body_models.py", line 906, in forward
>     right_hand_pose], dim=1)
> RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 2 and 3 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:62

When I set body type as 'smpl', the error is:

> Traceback (most recent call last):
> 
>   File "apps/genebody_fitting.py", line 197, in <module>
>     myrunner.run()
>   File "apps/genebody_fitting.py", line 187, in run
>     self.run_smplify(frame, data, keypoints)
>   File "apps/genebody_fitting.py", line 167, in run_smplify
>     use_mask=self.use_mask, masks=masks, mask_frames=mask_frames, output_folder=output_dir)
>   File "/home/wjh/nerf/code/bodyfitting/smplify/body_fitting.py", line 91, in __call__
>     use_mesh=use_mesh, meshfile=meshfile, displacement=disp)
>   File "/home/wjh/nerf/code/bodyfitting/smplify/smplify.py", line 187, in __call__
>     return_full_pose=True)
>   File "/home/wjh/anaconda3/envs/human/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/wjh/nerf/code/bodyfitting/models/smpl.py", line 71, in forward
>     smpl_output = super(SMPL, self).forward(*args, **kwargs)
>   File "/home/wjh/anaconda3/envs/human/lib/python3.6/site-packages/smplx/body_models.py", line 376, in forward
>     self.lbs_weights, pose2rot=pose2rot, dtype=self.dtype)
>   File "/home/wjh/anaconda3/envs/human/lib/python3.6/site-packages/smplx/lbs.py", line 179, in lbs
>     v_shaped = v_template + blend_shapes(betas, shapedirs)
>   File "/home/wjh/anaconda3/envs/human/lib/python3.6/site-packages/smplx/lbs.py", line 265, in blend_shapes
>     blend_shape = torch.einsum('bl,mkl->bmk', [betas, shape_disps])
>   File "/home/wjh/anaconda3/envs/human/lib/python3.6/site-packages/torch/functional.py", line 202, in einsum
>     return torch._C._VariableFunctions.einsum(equation, operands)
> RuntimeError: size of dimension does not match previous size, operand 1, dim 2

Both happen during the smpl forward in smplify/smplify.py line 179:
`smpl_output = self.smpl(global_orient=global_orient,
                            body_pose=body_pose,
                            betas=betas,
                            jaw_pose=jaw_pose,
                            leye_pose=leye_pose,
                            reye_pose=reye_pose,
                            left_hand_pose=left_hand_pose,
                            right_hand_pose=right_hand_pose,
                            return_full_pose=True)`

It seems like the shape of these pose tensors are mistaken? 
Looking forward to your reply.

**Comment by shanemankiw** [comment]
It seems the smplx version specified in the requirement smplx==0.1.13 is outdated. Fixed it by updating the smplx library to 0.1.28
